author = "Dom"
title = "Dom's website"
base_url = "https://m0thman70.github.io/doms-websitev2/"
compile_sass = true
build_search_index = false
generate_feed = true
minify_html = true


taxonomies = [
    { name = "tags", feed = true }
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]

[extra.papermod]
title = "Dom"
default_theme = "auto"
theme = "light"
language_direction = "auto"
keywords = ["keyword1", "keyword2", "keyword3"]
show_theme_toggle = true
show_scroll_to_top = true
show_code_copy_buttons = true
show_reading_time = true
show_word_count = false
show_post_nav_links = true
show_post_meta = true
default_toc_open = false
show_post_edit_button = false
#edit_post_url = "https://github.com/cydave/zola-theme-papermod/tree/master"
#copyright = ""
date_format = "%Y-%m-%d"
navigation = [
    { url = "$BASE_URL/tags", title = "Tags" },
    { url = "https://getzola.com/", title = "Zola", is_external = true }
]

home_title = "Greetings, Im Dom"
home_content = "<b>I still dont know how to make a website<b> <br>Brought to you by the Papermod zola theme by cydave"
social_icons = [
    { url = "https://github.com/m0thman70", title = "GitHub", icon = "github" },
    { url = "https://mastodon.social/@m0th05", title = "Mastodon", icon = "mastodon" },
    { url = "https://www.youtube.com/@m0th543", title = "Youtube", icon = "youtube" },
    { url = "https://codeberg.org", title = "codeberg", icon = "Codeberg" },
    { url = "discordapp.com/users/496981575158988801", title = "Discord", icon = "discord" },
    { url = "https://www.instagram.com/m0th05/", title = "Instgram", icon = "instagram" },
]